validation extension exercises
agarwalrashika00/depot_app pull request #6
Opened 2023-03-29 20:25 UTC by agarwalrashika00

In product model add validations for following
Permalink
-should be unique
-no special character and no space allowed
-minimum 3 words, separated by hyphen 
Price numericality validation should only run if price is present.
Description - should be between 5 and 10 words
Validate image_url format by using url:true(ActiveModel::EachValidator)
In product model, price should be greater than discount price
-using custom validator
-without custom validator

LineItems model
Combination of product_id and cart_id should be unique. Means one product can be added only once in the cart. If cart with cart_id exists.

Add following validations in user model
Uniqueness of email
Email format

2023-03-31 14:09 UTC, Ankita9818 requested changes

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/validators/url_validator.rb
> +end
always add a new line at EOD

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/product.rb
> +  validates :price, numericality: { greater_than_or_equal_to: 0.01 }, if: :price_present?
use validation options

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/product.rb
> +    with: /\A([\w]+-[\w]+(-)?){2,}\z/
move out in to constant

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/product.rb
> +  validates :description, length: {in: 5..10}
{ in: 5..10 }

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/product.rb
> +    price != nil
any alternate method to check this

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/user.rb
> +    with: /\A[\w-]+@[\w-]+\.(com|net|org)\z/
move regex out to constants.rb

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/validators/url_validator.rb
> +      record.errors.add :attribute, 'must be a URL for GIF, JPG or PNG image'
add i18n

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/product.rb
> +  validates :description, length: {in: 5..10}
fix this validation

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/line_item.rb
> +  validates_with UniqueCartProductValidator
Lets add uniqueness validator here instead of custom validator

2023-03-31 14:09 UTC, Ankita9818 commented on app/models/product.rb
> +  validates :image_url, allow_blank: true, url: true
try out 
validates :image_url, allow_blank: true

2023-04-04 11:04 UTC, agarwalrashika00 commented on app/models/product.rb
> +    price != nil
we can use price?

2023-04-12 13:24 UTC, Ankita9818 commented on app/models/product.rb
> +  validates :description, word_count: { in: 5..10 }
can we do this without custom validator?

2023-04-12 13:24 UTC, Ankita9818 commented on app/models/product.rb
> +  validates :price, numericality: { greater_than_or_equal_to: 0.01 }, allow_nil: true
why not allow_blank??

2023-04-12 13:24 UTC, Ankita9818 commented on app/models/product.rb
> +  validates :price, greater_than_discount: true, if: -> { discount_price? }
```suggestion
  validates :price, greater_than_discount: true, if: :discount_price?
```

2023-04-12 13:24 UTC, Ankita9818 commented on app/models/line_item.rb
> +    LineItem.validates :cart_id, uniqueness: { scope: :product_id }
why this??
From where are we following this pattern of writing validations in callback like this. Please fix

2023-04-12 13:24 UTC, Ankita9818 commented on app/models/user.rb
> +    with: EMAIL_REGEXP
we should not show format error if email is not present

2023-04-12 13:24 UTC, Ankita9818 commented on app/models/validators/greater_than_discount_validator.rb
> +      record.errors.add :price, "price should be greater than discount price"
use "" only for interpolation

2023-04-12 13:24 UTC, Ankita9818 commented on app/models/validators/url_validator.rb
> +    unless value =~ %r{\.(gif|jpg|png)\Z}i
regex should be a constant

2023-04-12 13:24 UTC, Ankita9818 commented on app/controllers/orders_controller.rb
> +        format.html { redirect_to store_index_url(locale: I18n.locale), notice: I18n.t('.thanks') }
Dont we need @order for store index url??
Lets use symbol instead of string in I18n.t

2023-04-12 13:24 UTC, Ankita9818 commented on config/initializers/constants.rb
> +EMAIL_REGEXP = /\A[\w-]+@[\w-]+\.(com|net|org)\z/
add new lines

2023-04-12 13:24 UTC, Ankita9818 commented on config/initializers/i18n.rb
> +["Espa&ntilde;ol".html_safe, 'es']
fix indentation

2023-04-18 07:08 UTC, Ankita9818 approved these changes

2023-04-18 07:08 UTC, merged